spring:
  application:
    name: syllabus-api
  datasource:
    url: jdbc:mysql://fms.cyfs9uuvm2c7.ap-northeast-1.rds.amazonaws.com:3306/FMS
    username: fms
    password: toandc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8768
  servlet:
    context-path: /syllabus-service
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-server-env.eba-cim7vrij.ap-northeast-1.elasticbeanstalk.com/eureka

aws:
  region: ap-northeast-1
  s3:
    bucket:
      customer: my-avatar
  cloud:
    aws:
      credentials:
        access-key: AKIASM2WECLH7AZGDAUV
        secret-key: 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

data:
  training: http://localhost:8769/training-program-service/api/trainingProgram
  class: http://localhost:8765/class-management/api/class
  user: http://localhost:8764/user-service/api/user
#  training: http://training-service-env.eba-qdz2same.ap-northeast-1.elasticbeanstalk.com/training-program-service/api/trainingProgram
#  class: http://class-service-env.eba-vfkp2siv.ap-northeast-1.elasticbeanstalk.com/class-management/api/class
#  user: http://user-service-env.eba-b2p73pwz.ap-northeast-1.elasticbeanstalk.com/user-service/api/user
