spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-api
          uri: http://localhost:8764
          predicates:
            - Path=/user-service/**
          filters:
            - AuthenticationFilter
        - id: class-api
          uri: http://localhost:8765
          predicates:
            - Path=/class-management/**
          filters:
            - AuthenticationFilter
        - id: training-api
          uri: http://localhost:8769
          predicates:
            - Path=/training-program-service/**
          filters:
            - AuthenticationFilter
        - id: syllabus-api
          uri: http://localhost:8768
          predicates:
            - Path=/syllabus-service/**
          filters:
            - AuthenticationFilter
#        - id: user-api
#          uri: http://user-service-env.eba-b2p73pwz.ap-northeast-1.elasticbeanstalk.com
#          predicates:
#            - Path=/user-service/**
#          filters:
#            - AuthenticationFilter
#        - id: class-api
#          uri: http://class-service-env.eba-vfkp2siv.ap-northeast-1.elasticbeanstalk.com
#          predicates:
#            - Path=/class-management/**
#          filters:
#            - AuthenticationFilter
#        - id: training-api
#          uri: http://training-service-env.eba-qdz2same.ap-northeast-1.elasticbeanstalk.com
#          predicates:
#            - Path=/training-program-service/**
#          filters:
#            - AuthenticationFilter
#        - id: syllabus-api
#          uri: http://syllabus-service-env.eba-ma3ik3wh.ap-northeast-1.elasticbeanstalk.com
#          predicates:
#            - Path=/syllabus-service/**
#          filters:
#            - AuthenticationFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credential Access-Control-Allow-Origin
      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-env.eba-cim7vrij.ap-northeast-1.elasticbeanstalk.com/eureka
server:
  port: 8080

#user-server-env.eba-6gyszq2i.ap-northeast-1.elasticbeanstalk.com
#class-server-env.eba-2aqy3a3i.ap-northeast-1.elasticbeanstalk.com
#eureka-server-env-1.eba-nweh2s3g.ap-northeast-1.elasticbeanstalk.com


