pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'https://index.docker.io/v1/'
        DOCKER_REPO = 'long2002/training'
    }

    tools {
        maven 'my-maven'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building the application...'
                catchError(buildResult: 'FAILURE') {
                    bat 'mvn clean install'

                }
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                catchError(buildResult: 'FAILURE') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                echo 'Packaging the application...'
                catchError(buildResult: 'FAILURE') {
                    bat 'mvn package'
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                  
                    catchError(buildResult: 'FAILURE') {
                        docker.withRegistry(DOCKER_REGISTRY, 'docker-demo') {
                        
                            bat "docker build -t ${DOCKER_REPO} ."
                        
                            bat "docker push ${DOCKER_REPO}"
                        }
                    }
                }
            }
        }
    }
}
